### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Sciss** [RobotnikAutomation/vmu931_imu#1]
Sorry to 'abuse' the issue tracker for this. I would like to enquire if you are using the VMC931 under Linux? I read there were some initial problems but that they have been fixed; I'm eying the VMC, so I want to be sure I see people using it successfully under Linux. Thanks

**Comment by RomanRobotnik** [comment]
Hi, so far I haven't detected any issue in Ubuntu 14.04 and 16.04.

Regards

**Comment by Sciss** [comment]
thank you!
